apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: cloudops
  name: cloudops
  namespace: cpaas-system
spec:
  containers:
  - image: cloudopscmd:v2
    name: cloudops
    resources: {}
    command:
     - sh
     - -c
     - sleep 3600
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

