# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
# https://juejin.cn/post/6844903928409096200

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run:  go build  -o bin/cloudopscmd -v main.go

    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: cloudopscmd
        path: /home/runner/work/cloudopscmd/cloudopscmd
        
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@master
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_SECRET }}

